// Code generated by gen/main.go; DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"

	"cloud.google.com/go/bigquery/datatransfer/apiv1/datatransferpb"
	"github.com/auifzysr/yabqsqcli/pkg/config"
	"github.com/auifzysr/yabqsqcli/pkg/domain"
	"github.com/auifzysr/yabqsqcli/pkg/factory"
	"github.com/urfave/cli/v2"
)

func callList(ctx context.Context, cfg *config.ListConfig) ([]*datatransferpb.TransferConfig, error) {
	var err error
	var res []*datatransferpb.TransferConfig

	tc, err := factory.ListTransferConfigFactory(cfg)
	if err != nil {
		return nil, err
	}
	itr := client.ListTransferConfigs(ctx, tc)
	for {
		m, err := itr.Next()
		if err != nil {
			break
		}
		res = append(res, m)
	}

	return res, nil
}

func list(cfg *config.ListConfig) error {
	ctx := context.Background()

	res, err := callList(ctx, cfg)
	if err != nil {
		return err
	}
	o, err := domain.Format(res, cfg.OutputFormat)
	if err != nil {
		return err
	}
	fmt.Printf("%s", o)

	return nil
}

func listCommand(rootCfg *config.RootConfig) *cli.Command {
	cfg := &config.ListConfig{
		RootConfig: rootCfg,
	}

	return &cli.Command{
		Name:        "list",
		Description: "list scheduled query config",
		Action: func(cCtx *cli.Context) error {
			return list(cfg)
		},
		Flags: []cli.Flag{},
	}
}
