// Code generated by gen/main.go; DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"

	"cloud.google.com/go/bigquery/datatransfer/apiv1/datatransferpb"
	"github.com/auifzysr/yabqsqcli/pkg/config"
	"github.com/auifzysr/yabqsqcli/pkg/domain"
	"github.com/auifzysr/yabqsqcli/pkg/factory"
	"github.com/urfave/cli/v2"
)

func list(cfg *config.ListConfig) error {
	tc, err := factory.ListTransferConfigFactory(cfg)
	if err != nil {
		return err
	}
	ctx := context.Background()

	var res []*datatransferpb.TransferConfig
	itr := client.ListTransferConfigs(ctx, tc)
	for {
		m, err := itr.Next()
		if err != nil {
			break
		}
		res = append(res, m)
	}
	f, err := domain.SelectFormatter(cfg.OutputFormat)
	if err != nil {
		return err
	}
	o, err := f.Format(res)
	if err != nil {
		return err
	}
	fmt.Printf("%s", o)

	return nil
}

func listCommand(rootCfg *config.RootConfig) *cli.Command {
	cfg := &config.ListConfig{
		RootConfig: rootCfg,
	}

	return &cli.Command{
		Name:        "list",
		Description: "list scheduled query config",
		Action: func(cCtx *cli.Context) error {
			return list(cfg)
		},
		Flags: []cli.Flag{},
	}
}
