// Code generated by gen/main.go; DO NOT EDIT.

package cmd

import (
	"context"
	"fmt"

	"cloud.google.com/go/bigquery/datatransfer/apiv1/datatransferpb"
	"github.com/auifzysr/yabqsqcli/pkg/config"
	"github.com/auifzysr/yabqsqcli/pkg/domain"
	"github.com/auifzysr/yabqsqcli/pkg/factory"
	"github.com/urfave/cli/v2"
)

func callRun(ctx context.Context, cfg *config.RunConfig) (*datatransferpb.StartManualTransferRunsResponse, error) {
	var err error
	var res *datatransferpb.StartManualTransferRunsResponse

	tc, err := factory.RunTransferConfigFactory(cfg)
	if err != nil {
		return nil, err
	}
	res, err = client.StartManualTransferRuns(ctx, tc)
	if err != nil {
		return nil, fmt.Errorf("run transfer failed: parent: %s, %w", fmt.Sprintf("projects/%s/locations/%s",
			cfg.ProjectID, cfg.Region,
		), err)
	}

	return res, nil
}

func run(cfg *config.RunConfig) error {
	ctx := context.Background()
	if cfg.TransferConfigID == "" {
		lcfg := &config.ListConfig{
			RootConfig: cfg.GetRootConfig(),
		}
		res, err := callList(ctx, lcfg)
		if err != nil {
			return err
		}

		candidates := domain.FindTransferConfigIDByName(res, func(m *datatransferpb.TransferConfig) bool {
			return m.DisplayName == cfg.GetDisplayName()
		})

		switch len(candidates) {
		case 0:
			return fmt.Errorf("no such scheduled query: %s", cfg.GetDisplayName())
		case 1:
			tcid, err := domain.GetTransferConfigIDByName(candidates[0].Name)
			if err != nil {
				return err
			}
			cfg.TransferConfigID = tcid
		default:
			return fmt.Errorf("pick either of these: %+v", candidates)
		}
	}

	res, err := callRun(ctx, cfg)
	if err != nil {
		return err
	}
	o, err := domain.Format(res, cfg.OutputFormat)
	if err != nil {
		return err
	}
	fmt.Printf("%s", o)

	return nil
}

func runCommand(rootCfg *config.RootConfig) *cli.Command {
	cfg := &config.RunConfig{
		RootConfig: rootCfg,
	}

	return &cli.Command{
		Name:        "run",
		Description: "run scheduled query config",
		Action: func(cCtx *cli.Context) error {
			return run(cfg)
		},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "config-id",
				Aliases:     []string{"c"},
				Value:       "",
				Usage:       "transfer config ID",
				Destination: &cfg.TransferConfigID,
			},
			&cli.StringFlag{
				Name:        "name",
				Aliases:     []string{"n"},
				Value:       "",
				Usage:       "name",
				Destination: &cfg.DisplayName,
			},
			&cli.StringFlag{
				Name:        "since",
				Aliases:     []string{"s"},
				Value:       "",
				Usage:       "since what past time running scheduled query, must be with --until in %Y-%m-%dT%H-%M-%SZ format",
				Destination: &cfg.Since,
			},
			&cli.StringFlag{
				Name:        "until",
				Aliases:     []string{"u"},
				Value:       "",
				Usage:       "until what past time running scheduled query, must be with --since in %Y-%m-%dT%H-%M-%SZ format",
				Destination: &cfg.Until,
			},
			&cli.StringFlag{
				Name:        "at",
				Aliases:     []string{"a"},
				Value:       "",
				Usage:       "at what time running scheduled query, in %Y-%m-%dT%H-%M-%SZ format",
				Destination: &cfg.At,
			},
		},
	}
}
