// Code generated by gen/main.go; DO NOT EDIT.

package config

type CreateConfig struct {
	*RootConfig

	DisplayName                       string
	Query                             string
	DestinationDatasetID              string
	DestinationTableID                string
	DestinationTablePartitioningField string
	DestinationTablePartitioningType  string
	WriteDisposition                  string
	Schedule                          string
	Disabled                          bool
	NotificationPubSubTopic           string
	NotificationSendEmail             bool
	ServiceAccountEmail               string
	StartTime                         string
	EndTime                           string
	EncryptionKeyRing                 string
	EncryptionKey                     string
}

func (c *CreateConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *CreateConfig) GetDisplayName() string {
	return c.DisplayName

}
