// Code generated by gen/main.go; DO NOT EDIT.

package config

type DeleteConfig struct {
	*RootConfig

	TransferConfigID string
	DisplayName      string
}

func (c *DeleteConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *DeleteConfig) GetDisplayName() string {
	return c.DisplayName

}
