// Code generated by gen/main.go; DO NOT EDIT.

package config

type GetConfig struct {
	*RootConfig

	TransferConfigID string
	DisplayName      string
}

func (c *GetConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *GetConfig) GetDisplayName() string {
	return c.DisplayName

}
