// Code generated by gen/main.go; DO NOT EDIT.

package config

type HistoryConfig struct {
	*RootConfig

	TransferConfigID string
	DisplayName      string
}

func (c *HistoryConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *HistoryConfig) GetDisplayName() string {
	return c.DisplayName

}
