// Code generated by gen/main.go; DO NOT EDIT.

package config

type ListConfig struct {
	*RootConfig
}

func (c *ListConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *ListConfig) GetDisplayName() string {
	return ""

}
