// Code generated by gen/main.go; DO NOT EDIT.

package config

type RunConfig struct {
	*RootConfig

	TransferConfigID string
	DisplayName      string
	Since            string
	Until            string
	At               string
}
