// Code generated by gen/main.go; DO NOT EDIT.

package config

type RunConfig struct {
	*RootConfig

	TransferConfigID string
	DisplayName      string
	Since            string
	Until            string
	At               string
}

func (c *RunConfig) GetRootConfig() *RootConfig {
	return c.RootConfig
}

func (c *RunConfig) GetDisplayName() string {
	return c.DisplayName

}
